version: "3.9"

services:
  php-fpm:
      image: php:8-fpm
      volumes:
          - ./backend:/var/www/html

  queue:
      image: php:8-fpm
      command:
        - php
        - artisan
        - queue:work
      volumes:
          - ./backend:/var/www/html

  api:
      image: nginx:latest
      ports:
        - '8080:80'
      volumes:
        - ./backend:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php-fpm

  web:
    build: ./docker/node
    ports:
      - '80:8080'
    volumes:
      - ./frontend:/app

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'  # Port 1025 => SMTP.
      - '8025:8025'  # Port 8025 => Web dashboard (http://127.0.0.1:8025).
