version: "3.9"

services:
  mysql:
      image: mysql:8
      command: ['--default-authentication-plugin=mysql_native_password']
      environment:
          MYSQL_DATABASE: local_db
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_PASSWORD: admin
          MYSQL_USER: admin
      volumes:
          - "/var/lib/mysql"
          - "./setup/developer/mysql/initdb:/docker-entrypoint-initdb.d"
      ports:
          - 3306:3306

  php-fpm:
      image: php:8-fpm
      volumes:
          - .:/var/www/html

  web:
      image: nginx:latest
      ports:
        - '8080:80'
      volumes:
        - .:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php-fpm

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'  # Port 1025 => SMTP.
      - '8025:8025'  # Port 8025 => Web dashboard (http://127.0.0.1:8025).
